import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Navbar from "./components/Navbar/Navbar";
import StoreProvider from "./components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={clsx(inter.className)}>
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 mt-20 mb-[120px]">
            {children}
          </div>
          <Navbar />
        </body>
      </html>
    </StoreProvider>
  );
}
