import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Navbar from "./components/Navbar/Navbar";
import AllProviders from "./AllProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AllProviders>
      <html lang="en">
        <body className={clsx(inter.className)}>
          <div className="container mx-auto">{children}</div>
        </body>
        <Navbar />
      </html>
    </AllProviders>
  );
}
